### PR TITLE
Solve errors in quantum_erasure module

### PR DESCRIPTION
**Pull request by Magalame**
There's still the problem of the tests failing though

### CODE REVIEW

**Comment by Magalame** [comment]
I think there might be a problem with the way the stabilizers are stored. Eg, with 

```rust
use believer::{GF4Stabilizers};
use believer::Pauli::{I, X, Z};


fn main() {

    let stabilizers = GF4Stabilizers::from_sparse_paulis(
            vec![
                vec![(Z, 0), (Z, 1)],
                vec![(Z, 1), (Z, 2)],
                vec![(Z, 3), (Z, 4)],
                vec![(Z, 4), (Z, 5)],
                vec![(Z, 6), (Z, 7)],
                vec![(Z, 7), (Z, 8)],
                vec![(X, 0), (X, 1), (X, 2), (X, 3), (X, 4), (X, 5)],
                vec![(X, 3), (X, 4), (X, 5), (X, 6), (X, 7), (X, 8)],
            ],
            9,
        );


    println!("Shor's code stabilizer:");

    println!("x:{:?}",stabilizers.x_checks());
    println!("z:{:?}",stabilizers.z_checks());

    let stabilizers = GF4Stabilizers::from_dense_paulis(
            vec![
                vec![X, Z, Z, X, I],
                vec![I, X, Z, Z, X],
                vec![X, I, X, Z, Z],
                vec![Z, X, I, X, Z],
            ],
            5,
        );

    println!("5 qubits code stabilizer:");
    
    println!("x:{:?}",stabilizers.x_checks());
    println!("z:{:?}",stabilizers.z_checks());

}
```

prints

```
Shor's code stabilizer:
x:ParityCheckMatrix { check_ranges: [0, 6, 12], bit_indices: [0, 1, 2, 3, 4, 5, 3, 4, 5, 6, 7, 8], n_bits: 9 }
z:ParityCheckMatrix { check_ranges: [0, 2, 4, 6, 8, 10, 12], bit_indices: [0, 1, 1, 2, 3, 4, 4, 5, 6, 7, 7, 8], n_bits: 9 }
5 qubits code stabilizer:
x:ParityCheckMatrix { check_ranges: [0, 2, 4, 6, 8], bit_indices: [0, 3, 1, 4, 0, 2, 1, 3], n_bits: 5 }
z:ParityCheckMatrix { check_ranges: [0, 2, 4, 6, 8], bit_indices: [1, 2, 2, 3, 3, 4, 0, 4], n_bits: 5 }
```
Which seems to suggest that there is no distinction made between a raw quantum code, and a CSS code.

**Comment by Magalame** [comment]
For example this:
```rust
let stabilizers = GF4Stabilizers::from_dense_paulis(
            vec![
                vec![X, Z, Z, X, I],
                vec![I, X, Z, Z, X],
                vec![X, I, X, Z, Z],
                vec![Z, X, I, X, Z],
            ],
            5,
        );

    println!("5 qubits code stabilizer:");
    
    println!("x:{:?}",stabilizers.x_checks());
    println!("z:{:?}",stabilizers.z_checks());

    let stabilizers = GF4Stabilizers::from_dense_paulis(
            vec![
                vec![I, Z, Z, I, I],
                vec![I, I, Z, Z, I],
                vec![I, I, I, Z, Z],
                vec![Z, I, I, I, Z],

                vec![X, I, I, X, I],
                vec![I, X, I, I, X],
                vec![X, I, X, I, I],
                vec![I, X, I, X, I],
            ],
            5,
        );

    println!("5 qubits code but CSS:");
    
    println!("x:{:?}",stabilizers.x_checks());
    println!("z:{:?}",stabilizers.z_checks());
```

prints

```
5 qubits code stabilizer:
x:ParityCheckMatrix { check_ranges: [0, 2, 4, 6, 8], bit_indices: [0, 3, 1, 4, 0, 2, 1, 3], n_bits: 5 }
z:ParityCheckMatrix { check_ranges: [0, 2, 4, 6, 8], bit_indices: [1, 2, 2, 3, 3, 4, 0, 4], n_bits: 5 }
5 qubits code but CSS:
x:ParityCheckMatrix { check_ranges: [0, 2, 4, 6, 8], bit_indices: [0, 3, 1, 4, 0, 2, 1, 3], n_bits: 5 }
z:ParityCheckMatrix { check_ranges: [0, 2, 4, 6, 8], bit_indices: [1, 2, 2, 3, 3, 4, 0, 4], n_bits: 5 }
```
While they should be different codes, and it should read

```
5 qubits code stabilizer:
x:ParityCheckMatrix { check_ranges: [0, 2, 4, 6, 8], bit_indices: [0, 3, 1, 4, 0, 2, 1, 3], n_bits: 5 }
z:ParityCheckMatrix { check_ranges: [0, 2, 4, 6, 8], bit_indices: [1, 2, 2, 3, 3, 4, 0, 4], n_bits: 5 }
5 qubits code but CSS:
x:ParityCheckMatrix { check_ranges: [0, 0, 0, 0, 0, 0, 2, 4, 6, 8], bit_indices: [0, 3, 1, 4, 0, 2, 1, 3], n_bits: 5 }
z:ParityCheckMatrix { check_ranges: [0, 2, 4, 6, 8, 8, 8, 8, 8, 8], bit_indices: [1, 2, 2, 3, 3, 4, 0, 4], n_bits: 5 }

**Comment by Magalame** [comment]
Unfortunately even the 5 qubit code test doesn't work, so there's also something wrong somewhere else :/

**Comment by Magalame** [comment]
The CSS/non CSS problem seems to be resolved when commenting out the length check in `fill_with` in the`ParityCheckMatrix` module:

```rust
fn fill_with(&mut self, checks: Vec<Check>) {
        checks.into_iter().for_each(|check| {
           // if check.len() > 0 {
                self.add_check(check)
          //  }
        });
    }
```

**Comment by Magalame** [comment]
This also resolves all the tests!

**Review by maxtremblay — APPROVED** [review]

**Pull request merged**
